//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcode_data
    {
        public int id { get; set; }
        public string item_name { get; set; }
        public int item_length { get; set; }
        public decimal item_x { get; set; }
        public decimal item_y { get; set; }
        public string type { get; set; }
        public bool is_numeric { get; set; }
        public string format { get; set; }
        public string font { get; set; }
        public int font_size { get; set; }
        public bool is_bold { get; set; }
        public string font_color { get; set; }
        public bool is_italic { get; set; }
    }
}
