//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcode_print
    {
        public int id { get; set; }
        public decimal start_x { get; set; }
        public decimal b_width { get; set; }
        public decimal b_height { get; set; }
        public decimal v_gap { get; set; }
        public decimal h_gap { get; set; }
        public decimal start_y { get; set; }
    }
}
